services:

  # APPLICATION LAYER USE CASES
  
  agency.prompt_agent_use_case:
    class: application.agency.PromptAgentUseCase
    arguments: ['@agency.agent_factory']

  agency.run_discord_bot_use_case:
    class: application.agency.RunDiscordBotUseCase
    arguments: ['@agency.prompt_agent_use_case']

  agency.index_documents_use_case:
    class: application.agency.IndexDocumentsUseCase
    arguments: ['@agency.indexer']

  # AGENCY IMPLEMENTATIONS
  
  agency.agent_factory:
    class: infrastructure.agency.AgentFactory
    arguments: ['@agency.tool_factory']

  agency.tool_factory:
    class: infrastructure.agency.ToolFactory
  
  agency.agent.scheduling:
    class: infrastructure.agency.SchedulingAgent
    tags:
      - { name: agent, alias: scheduling }

  agency.indexer:
    class: infrastructure.ext.faiss.FAISSIndexer
    arguments: 
      docs_path: '%OBSIDIAN_VAULT_PATH%'
      chunk_size: 1000
      chunk_overlap: 100
      save_path: '%FAISS_INDEX_PATH%'